<?php
/**
 * @file
 * Hooks implementations.
 */

/**
 * Define the CKEditor plugin. *
 * Implements hook_ckeditor_plugin().
 *
 * @return array
 *   CKEditor settings.
 */
function ckeditor_source_plugin_ckeditor_plugin() {
  return array(
    'sourceit' => array(
      'name' => 'sourceit',
      'desc' => t('CKEditor Source it Plugin : Allow to source facts'),
      'path' => drupal_get_path('module', 'ckeditor_source_plugin') . '/sourceit/',
      'buttons' => array(
        'sourceit' => array(
          'icon' => 'images/sourceit.png',
          'label' => t('Add a source'),
        ),
      ),
    ),
  );
}

/**
 * Extend CKEditor's settings.
 * Implements hook_ckeditor_settings_alter().
 *
 * @param array $settings
 *   CKEditor base settings.
 * @param array $conf
 *   CKEditor configuration.
 */
function ckeditor_source_plugin_ckeditor_settings_alter(array &$settings, array $conf) {
  if (isset($settings['js_conf']['extraAllowedContent'])) {
    $settings['js_conf']['extraAllowedContent'] .= "'a(*);span(*);'";
  }
  else {
    $settings['js_conf']['extraAllowedContent'] = "'a(*);span(*);'";
  }
}